In [47]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sn 
import warnings
warnings.filterwarnings('ignore')

In [48]:
df = sn.load_dataset('iris')
df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [49]:
print(df['species'].unique())

['setosa' 'versicolor' 'virginica']

In [50]:
from sklearn.model_selection import train_test_split

In [51]:
X = df.drop('species',axis = 1)
y = df['species']

In [52]:
X_train, X_test, y_train, y_test = train_test_split( X, y, test_size=0.33, random_state=42)

In [53]:
from sklearn.neighbors import KNeighborsClassifier

In [54]:
model_knn =  KNeighborsClassifier(n_neighbors=13)
model_knn.fit(X_train , y_train)

KNeighborsClassifier(n_neighbors=13)

In [55]:
model_knn.score(X_test, y_test) # model of knn -> overfit cond

1.0

In [56]:
from sklearn.svm import SVC

In [57]:
model_svm = SVC(C= 10 , kernel= 'linear' , gamma='auto') # prev hyperparameter -> C= 30 , kernel= 'rbf'
model_svm.fit(X_train , y_train)

SVC(C=10, gamma='auto', kernel='linear')

In [58]:
model_knn.score(X_test , y_test) # -> diff parameter model Overfit

1.0

# Grid Search CV
### WHEN TO USE GRIDSEARCHCV

> Use Grid Search when:

* Small Search Space
* Small Dataset
* Best combination from provided grid

In [59]:
from sklearn.model_selection import GridSearchCV

In [78]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC

model_svm = SVC()

classifier_svm = GridSearchCV(
    
    estimator=model_svm,
    
    param_grid={
        'C': [1, 10, 20, 30],  # Penalty for wrong classification
        
        'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
    },
    
    cv=5,
    
    return_train_score=False
)

classifier.fit(X, y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 10, 20, 30],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [79]:
results = pd.DataFrame(classifier.cv_results_)
results.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006309,0.001156,0.005323,0.001036,1,linear,"{'C': 1, 'kernel': 'linear'}",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,1
1,0.004584,0.002713,0.002668,0.000999,1,poly,"{'C': 1, 'kernel': 'poly'}",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,1
2,0.002564,0.000024,0.001945,0.000012,1,rbf,"{'C': 1, 'kernel': 'rbf'}",0.966667,0.966667,0.966667,0.933333,1.000000,0.966667,0.021082,7
3,0.002651,0.000823,0.001665,0.000729,1,sigmoid,"{'C': 1, 'kernel': 'sigmoid'}",0.033333,0.166667,0.000000,0.100000,0.033333,0.066667,0.059628,13
4,0.005079,0.003133,0.003856,0.002573,10,linear,"{'C': 10, 'kernel': 'linear'}",1.000000,1.000000,0.900000,0.966667,1.000000,0.973333,0.038873,5

In [80]:
results[['param_C', 'param_kernel', 'mean_test_score' ]]

    param_C param_kernel  mean_test_score
0         1       linear         0.980000
1         1         poly         0.980000
2         1          rbf         0.966667
3         1      sigmoid         0.066667
4        10       linear         0.973333
5        10         poly         0.966667
6        10          rbf         0.980000
7        10      sigmoid         0.053333
8        20       linear         0.966667
9        20         poly         0.966667
10       20          rbf         0.980000
11       20      sigmoid         0.040000
12       30       linear         0.960000
13       30         poly         0.966667
14       30          rbf         0.973333
15       30      sigmoid         0.040000

In [81]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

pipe = Pipeline([
    ('scaler', StandardScaler()), 
    ('svm', SVC())
])

params = {
    'svm__C': [1, 10, 20, 30],
    'svm__kernel': ['linear', 'poly', 'rbf', 'sigmoid']
}

grid_svm = GridSearchCV(
    estimator=pipe,
    param_grid=params,
    cv=5,
    scoring='accuracy',
    n_jobs=-1
)

grid.fit(X_train, y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('scaler', StandardScaler()),
                                       ('svm', SVC())]),
             n_jobs=-1,
             param_grid={'svm__C': [1, 10, 20, 30],
                         'svm__kernel': ['linear', 'poly', 'rbf', 'sigmoid']},
             scoring='accuracy')

In [83]:
grid_df = pd.DataFrame(grid.cv_results_)
grid_df.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_svm__C,param_svm__kernel,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011640,0.002833,0.005760,0.001486,1,linear,"{'svm__C': 1, 'svm__kernel': 'linear'}",1.00,0.8,0.90,1.0,0.95,0.93,0.074833,1
1,0.012245,0.004660,0.006522,0.002185,1,poly,"{'svm__C': 1, 'svm__kernel': 'poly'}",0.85,0.9,0.95,1.0,0.75,0.89,0.086023,13
2,0.009895,0.001803,0.005668,0.001195,1,rbf,"{'svm__C': 1, 'svm__kernel': 'rbf'}",1.00,0.8,0.90,1.0,0.95,0.93,0.074833,1
3,0.011561,0.001099,0.006840,0.001105,1,sigmoid,"{'svm__C': 1, 'svm__kernel': 'sigmoid'}",1.00,0.9,0.75,1.0,0.90,0.91,0.091652,8
4,0.010751,0.002162,0.007582,0.001205,10,linear,"{'svm__C': 10, 'svm__kernel': 'linear'}",0.95,0.8,0.90,1.0,1.00,0.93,0.074833,1

In [84]:
grid_df[['param_svm__C' , 'param_svm__kernel', 'mean_test_score']]

    param_svm__C param_svm__kernel  mean_test_score
0              1            linear             0.93
1              1              poly             0.89
2              1               rbf             0.93
3              1           sigmoid             0.91
4             10            linear             0.93
5             10              poly             0.91
6             10               rbf             0.93
7             10           sigmoid             0.84
8             20            linear             0.93
9             20              poly             0.91
10            20               rbf             0.92
11            20           sigmoid             0.82
12            30            linear             0.93
13            30              poly             0.91
14            30               rbf             0.91
15            30           sigmoid             0.83

In [86]:
classifier_knn = GridSearchCV(
    estimator=model_knn, 
    param_grid = {
        'n_neighbors' : [3,5,7,9,11], 
        'weights' : ['uniform', 'distance'] , 
        'algorithm' : ['auto', 'ball_tree', 'kd_tree', 'brute'], 
        'leaf_size': [10, 20, 30, 40, 50], 
        'metric': ['minkowski', 'euclidean', 'manhattan'], 
        'p' : [1,2]
    } , 
    cv = 5 , scoring= 'accuracy' , n_jobs=-1
)

In [87]:
classifier_knn.fit(X , y )

GridSearchCV(cv=5, estimator=KNeighborsClassifier(n_neighbors=13), n_jobs=-1,
             param_grid={'algorithm': ['auto', 'ball_tree', 'kd_tree', 'brute'],
                         'leaf_size': [10, 20, 30, 40, 50],
                         'metric': ['minkowski', 'euclidean', 'manhattan'],
                         'n_neighbors': [3, 5, 7, 9, 11], 'p': [1, 2],
                         'weights': ['uniform', 'distance']},
             scoring='accuracy')

In [89]:
knn_best_params = pd.DataFrame(classifier_knn.cv_results_)
knn_best_params.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_algorithm,param_leaf_size,param_metric,param_n_neighbors,param_p,param_weights,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.011167,0.004196,0.015027,0.003945,auto,10,minkowski,3,1,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'metric...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,574
1,0.010249,0.002448,0.011356,0.002284,auto,10,minkowski,3,1,distance,"{'algorithm': 'auto', 'leaf_size': 10, 'metric...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,574
2,0.010844,0.001334,0.017060,0.001431,auto,10,minkowski,3,2,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'metric...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,574
3,0.008973,0.001404,0.010197,0.001965,auto,10,minkowski,3,2,distance,"{'algorithm': 'auto', 'leaf_size': 10, 'metric...",0.966667,0.966667,0.933333,0.966667,1.0,0.966667,0.021082,574
4,0.009145,0.002007,0.012299,0.001518,auto,10,minkowski,5,1,uniform,"{'algorithm': 'auto', 'leaf_size': 10, 'metric...",0.966667,0.966667,0.900000,0.966667,1.0,0.960000,0.032660,871

In [91]:
knn_best_params[['param_n_neighbors' , 'param_weights' ,'param_algorithm' , 'param_leaf_size' , 'param_metric' , 'param_p' , 'mean_test_score']]

,param_n_neighbors,param_weights,param_algorithm,param_leaf_size,param_metric,param_p,mean_test_score
0,3,uniform,auto,10,minkowski,1,0.966667
1,3,distance,auto,10,minkowski,1,0.966667
2,3,uniform,auto,10,minkowski,2,0.966667
3,3,distance,auto,10,minkowski,2,0.966667
4,5,uniform,auto,10,minkowski,1,0.960000
...,...,...,...,...,...,...,...
1195,9,distance,brute,50,manhattan,2,0.960000
1196,11,uniform,brute,50,manhattan,1,0.980000
1197,11,distance,brute,50,manhattan,1,0.966667
1198,11,uniform,brute,50,manhattan,2,0.980000
1199,11,distance,brute,50,manhattan,2,0.966667

# Random Search CV
### Use Random Search when:
> Large Hyperparameter Space

*5 × 5 × 4 × 3 × 4
= 1200 combinations

In [92]:
from sklearn.model_selection import RandomizedSearchCV

In [98]:
classifier_random = RandomizedSearchCV(
    
    estimator=model_svm,

    param_distributions={
        'C': [1, 10, 20, 30],  # Penalty for wrong classification
        
        'kernel': ['linear', 'poly', 'rbf', 'sigmoid']
    },
    n_iter=4, 
    cv=5,
    
    return_train_score=False
)

classifier_random.fit(X, y)

RandomizedSearchCV(cv=5, estimator=SVC(), n_iter=4,
                   param_distributions={'C': [1, 10, 20, 30],
                                        'kernel': ['linear', 'poly', 'rbf',
                                                   'sigmoid']})

In [99]:
classifier_random = pd.DataFrame(classifier_random.cv_results_)
classifier_random.head()

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_kernel,param_C,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.005884,0.002685,0.003651,0.000632,linear,20,"{'kernel': 'linear', 'C': 20}",1.000000,1.000000,0.900000,0.933333,1.000000,0.966667,0.042164,2
1,0.002721,0.000152,0.001997,0.000074,linear,1,"{'kernel': 'linear', 'C': 1}",0.966667,1.000000,0.966667,0.966667,1.000000,0.980000,0.016330,1
2,0.003862,0.000055,0.002326,0.000211,sigmoid,1,"{'kernel': 'sigmoid', 'C': 1}",0.033333,0.166667,0.000000,0.100000,0.033333,0.066667,0.059628,4
3,0.002898,0.000060,0.002239,0.000180,rbf,1,"{'kernel': 'rbf', 'C': 1}",0.966667,0.966667,0.966667,0.933333,1.000000,0.966667,0.021082,2

In [100]:
classifier_random[['param_kernel', 'param_C', 'mean_test_score']]

  param_kernel  param_C  mean_test_score
0       linear       20         0.966667
1       linear        1         0.980000
2      sigmoid        1         0.066667
3          rbf        1         0.966667